# Generated by Django 5.1.1 on 2024-09-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_book_quantiy_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_returnd',
            field=models.BooleanField(default=False),
        ),
    ]
