# Generated by Django 5.1.1 on 2024-09-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_remove_book_quantiy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='is_returnd',
            new_name='is_returned',
        ),
    ]
