version: '3.8'

services:
  inter_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: interview_beat
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: 123

  django:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
      - celerybeat
      - inter_db

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - inter_db

  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A config beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - inter_db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
